### ISSUE TITLE
Invalid file header signature

### ISSUE THREAD

**Issue by marcelaraujo** [xdevl/node-apk#3]
Hi,

I was just giving a try on your library and I found an issue when I tried to read the Google Messaging APK.

> Error: Invalid file header signature found: 0x2014b50
>    at new ZipEntry (.../node_modules/node-apk/build/lib/zip.js:29:19)
>    at .../node_modules/node-apk/build/lib/zip.js:74:29

Can you help me figure out what is happening?

**Comment by xdevl** [comment]
Hi there,
Could you please share a link where I could download the APK from so I can investigate further ? In the meanwhile I would also suggest to try with a couple of APKs downloaded from different sources and different version to see if it makes any difference.

**Comment by marcelaraujo** [comment]
It only happens with this APK of Google Messaging. I tried different versions and it happens too.

I got them from here.

https://www.apkmirror.com/apk/google-inc/messenger-google-inc/

If you help me to fix this issue, I can see what you've done and try to fix some issues in the future.

Best regards

**Comment by xdevl** [comment]
Thank you for reporting the issue, the problem has now been solved in version 1.1.1 and was mostly caused by APK files embedding zip files, you can refer to the relevant commit for more details. Hope this solves your problem, otherwise please do let me know.
