### ISSUE TITLE
cert bytes output garbled code

### ISSUE THREAD

**Issue by Barryhuan** [xdevl/node-apk#5]
cert.bytes.toString("utf8") 

╔╔╔║╚��0��╗���zX��rĳy���v^�ӮƟ�b�b.b�G�DK{i^Tқ}���dy0����wis�h���g&�(nW�)Lv���A��6��ઐ�^��I�{�[m;S���-x���
��.��+�
╔╔║║╚��c#���╔�\��
�����������Z�
��e�Ʌ3J8�,g�z���KQ�═)hsG������su�2T��c��s6��&�L�v�;���\�z+�i�u�|ڣ7��8rjw����       ����&��h�

**Comment by xdevl** [comment]
The bytes property contains the raw bytes of the certificate in its DER form so it isn't something that is supposed to be read as text. You can either:
* save the cert bytes into a file to read it / convert it using openssl
```
openssl x509 -in [your cert file here] -inform der -noout -text
```
* turn it into a pem certificate that can be displayed as text:
```
const pemCert = `-----BEGIN CERTIFICATE-----\n${cert.bytes.toString("base64")}\n-----END CERTIFICATE-----`
```

**Comment by Barryhuan** [comment]
Thank you very much, because the project needs to read the signature fingerprint of APK, I don't know whether this project can read

**Comment by xdevl** [comment]
If it is a fingerprint you are after, what you will more likely want to do is hash those bytes as sha1 or md5 (depending on how your fingerprint is defined) to compare them to your fingerprint.

**Comment by Barryhuan** [comment]
Thank you. I'll try it now

**Comment by Barryhuan** [comment]
Sorry, I'm a novice. I don't know how to convert this to md5 or sha1. At present, only these two values are needed
![6aa2dfcfe4d84ab772a0dcc013f6aee](https://user-images.githubusercontent.com/46715367/205023103-43d5ac17-5821-42d1-bf96-52b441874198.jpg)

**Comment by Barryhuan** [comment]
Thank you. I've found a way，openssl x509 -fingerprint -in cert.pem -inform der -MD5 | -SHA1

**Comment by xdevl** [comment]
There should be plenty of information on the internet to describe how to compute a hash from a sequence of bytes :) If what you are after is the public key fingerprint though (ie: not the fingerprint of the whole certificate) you'll need to extract the public key from the cert. You'll more likely need to use [node-forge](https://www.npmjs.com/package/node-forge#x509) for this.

**Comment by Barryhuan** [comment]
Thank you. I'll try this method too
